CCI-Tools/cate-app

.gitignore
package.json
public/index.html
src/index.tsx
yarn.lock

closes #10

---

public/index.html
src/renderer/actions.ts
src/renderer/containers/AppBar.tsx
src/renderer/containers/StatusBar.tsx
src/renderer/containers/WebAPIStatusBox.tsx
src/renderer/webapi/HttpError.ts
src/renderer/webapi/apis/AuthAPI.ts

**Note**: I expect you to read at least what has changed (the list below). It is ok, if you don't review the code changes in detail.
- Center status icon  in Web API box
- Removed console warning saying that \<div\> cannot be in \<p\>

Forman 4 mode issues

---

src/renderer/containers/AppBar.tsx
src/renderer/containers/WorkspacesMenu.tsx

Changes:
* Workspaces menu is now fully functional
* Closes #20

Implemented workspaces menu

---

package.json
src/renderer/actions.ts
src/renderer/containers/AppBar.tsx
src/renderer/containers/AppModePage.tsx
src/renderer/containers/PreferencesDialog.tsx
src/renderer/containers/WorkspacesMenu.tsx
src/renderer/initial-state.ts
src/renderer/reducers.ts
src/renderer/state.ts
src/renderer/webapi/apis/ServiceInfoAPI.ts

In this PR:
- Fixes some sub-issues of #4 so it can be closed
- Added about panel in preferences dialog, so this also closes #26 
I will merge this now, because we need a formal release today.

Release of 2.1.0-dev.2

---

src/renderer/containers/DataAccessComponent.tsx
src/renderer/containers/DataSourcesPanel.tsx
src/renderer/initial-state.ts
src/renderer/selectors.spec.ts
src/renderer/selectors.ts
src/renderer/state.ts

Contains minor adjustments related to https://github.com/CCI-Tools/cate/pull/882

show data source titles instead of ids

---

package.json
src/renderer/actions.ts
src/renderer/components/cesium/cesium-util.ts
src/renderer/containers/PlacemarksPanel.tsx
yarn.lock

- When accepting this PR the clipboard will work in non-electron mode.
- When adding a polygon the application won't break anymore by reporting non-existent  holes.

Dzelge 41 clipboard

---

src/renderer/components/cesium/CesiumGlobe.tsx
src/renderer/components/cesium/cesium-util.ts
src/renderer/components/cesium/geometry-tool.ts
src/renderer/containers/PlacemarksPanel.tsx

Fixes some of the Cesium issues. Selection remains broken.

Forman 11 fix cesium

---

src/renderer/containers/PlacemarksPanel.tsx

When accepting this PR, the places panel context menu will be reintroduced

Dzelge 11 contextmenu

---

CHANGES.md
package.json
src/remoteStorage.ts
src/renderer/actions.ts
src/renderer/containers/PreferencesDialog.tsx
src/renderer/initial-state.ts
src/renderer/main.tsx
src/renderer/selectors.ts
src/renderer/typedStorage.ts
yarn.lock

When accepting this PR, cate-webui will use remote user preferences

Is now using the Cate Web API to handle user preferences

---

src/renderer/components/cesium/cesium-util.ts
src/renderer/state-util.ts

Closes #11 with Web API update, i.e. given that https://github.com/CCI-Tools/cate/pull/913 is merged.

Make Polyline/Polygon-Drawing work again

---

src/renderer/containers/JobFailureDialog.tsx
src/renderer/containers/OperationStepDialog.tsx
src/renderer/containers/editor/BooleanValueEditor.tsx
src/renderer/containers/editor/InputEditor.tsx

Fixes some sub-issues of Issue #12

Fixes for some GUI glitches introduced by blueprint 3 upgrade

---

CHANGES.md
src/renderer/components/ToolButton.tsx
src/renderer/containers/StylesPanel.tsx

This PR fixes the problem of scrolling through the colormaps described in #12 and has been reviewed via skype, therefore merging directly.

colorbar scroll

---

CHANGES.md
src/renderer/actions.ts
src/renderer/components/cesium/CesiumGlobe.tsx
src/renderer/components/cesium/cesium-util.ts
src/renderer/containers/GlobeView.tsx
src/renderer/containers/LayersPanel.tsx
src/renderer/containers/StylesPanel.tsx
src/renderer/containers/ViewPanel.tsx
src/renderer/initial-state.ts
src/renderer/reducers.ts
src/renderer/selectors.ts
src/renderer/state-util.ts
src/renderer/state.ts

Verify:
1. change base map, make sure it is different from default, e.g. 'Dark'
2. create new view. it should use the last base map, e.g. 'Dark'

Add new base layers

---

src/renderer/containers/AppBar.tsx
src/renderer/containers/HelpMenu.tsx

Add help menu

---

CHANGES.md
src/renderer/containers/PreferencesDialog.tsx

This PR makes word breaks in the about section possible.

wrap content of 'About' section

---

CHANGES.md
src/renderer/components/cesium/cesium-util.ts

Forman 116 fix style crash

---

CHANGES.md
src/renderer/containers/DataSourcesPanel.tsx
src/renderer/messages.tsx

In this PR:
* The DATA SOURCES panel now indicates by a progress spinner that data sources are being fetched. (#126)
* Fixed bug, where no data sources were shown right after start (#56)

DATA SOURCES panel updates

---

CHANGES.md
src/renderer/actions.ts
src/renderer/components/DataSourceDetails.tsx
src/renderer/components/DataSourceItem.tsx
src/renderer/components/DataSourceLinks.tsx
src/renderer/components/DataSourceOpenHint.tsx
src/renderer/components/DataSourcesList.tsx
src/renderer/containers/DataAccessComponent.tsx
src/renderer/containers/DataSourcesPanel.tsx
src/renderer/initial-state.ts
src/renderer/reducers.ts
src/renderer/selectors.ts
src/renderer/state-util.ts
src/renderer/state.ts
src/renderer/webapi/apis/DatasetAPI.ts

* The DATA SOURCES panel has been updated:
- Fixed deferred effect of checkbox "Show identifiers"
- Added checkbox "All data sources" that will display all ODP datasets
- Added warn icon to those datasets that cannot be opened from store.
Such data sources disable the "Open" button and display a popup 
instead. The popup informs the user how to manually download and open 
the datasets. 
* Using term "sandboxed file system" instead of "user root" in about box

Verification Flags

---

.env
CHANGES.md
Dockerfile
src/common/cate-types.ts
src/renderer/components/field/Field.tsx
src/renderer/containers/editor/TextValueEditor.tsx
src/renderer/containers/editor/ValueEditor.tsx
src/renderer/state.ts
src/renderer/webapi/apis/OperationAPI.ts

When accepting this PR the cate op read_zarr dialog will use the type Password for the bucket secret or token.

Dzelge 973 hide secrets

---

.dockerignore
.env
Dockerfile
README.md
src/config.ts
src/renderer/actions.ts
src/renderer/containers/PreferencesDialog.tsx
src/renderer/containers/VersionTags.tsx
src/renderer/main.tsx
src/renderer/webapi/apis/ServiceProvisionAPI.ts
src/version.ts

- Simplified and concentrated app configuration.
- Simplified Dockerfile.

Simplified app configuration and Dockerfile

---

CHANGES.md
src/config.ts
src/renderer/containers/DataAccessComponent.tsx
src/renderer/containers/PreferencesDialog.tsx
src/renderer/state.ts
src/renderer/webapi/apis/ServiceInfoAPI.ts

Renamed "About" tab in Preferences Dialog into "System". There we now also display the versions of Cate's core Python package dependencies:

Show Cate's core Python dependencies

---

CHANGES.md
appveyor.yml
package.json
src/config.ts
src/renderer/actions.ts
src/serviceWorker.ts

Prepare 3.0.1 release with workaround for #156

---

.github/workflows/build.yml

The HG actions workflow was using the wrong app name. When accepting this PR the name should be corrected.

Dzelge xxx workflow wrong appname

---

.github/workflows/build.yml

Should fix faulty update of k8s-configs:
- Environment variables are set
- Redundant entry for updating cate in k8s-configs has been removed

Set env variables

---

CHANGES.md
src/renderer/containers/ServiceAutoCloseDialog.tsx
src/renderer/containers/WebAPIStatusBox.tsx

Changed the time until the message is shown that Cate will automatically shut down due to inactivity.
Addresses #150.

Adjust auto-shutdown message
